---
- name: Create Linux VMs
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "node-{{ item }}"
    vm_size: "{{ size_worker }}"
    admin_username: azureuser
    ssh_password_enabled: no
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: "{{ ssh_key }}"
    network_interfaces: "nic-internal{{ item }}"
    os_type: Linux
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 18.04-LTS
      version: latest
  async: 300
  poll: 0
  register: linux_deploy
  with_sequence: "start=1 count={{ amount_worker + 1 }}"

# Wait for other long running tasks
- name: Check Linux VM creation status
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 300
  delay: 10
  loop: "{{ linux_deploy.results }}"