---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: canadaeast

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: vnet
    address_prefixes_cidr: "10.0.0.0/16"

- name: Create internal subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: vnet-internal
    address_prefix_cidr: "10.0.0.0/24"
    virtual_network: vnet

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: public-ip
  register: output_ip

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip.state.ip_address }}"

- name: Export IP Address
  copy:
    content: "{{ output_ip.state.ip_address }}"
    dest: "creds/ip"

- name: Calculate number of interfaces requiered (No test)
  set_fact:
    network_count: "{{ amount_worker + 1 }}"
  when: test_vm == false

- name: Calculate number of interfaces requiered (With test)
  set_fact:
    network_count: "{{ amount_worker + 2 }}"
  when: test_vm == true

- name: Create network interfaces ({{ network_count }})
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "nic-internal{{ item }}"
    virtual_network: vnet
    subnet_name: "vnet-internal"
    create_with_security_group: no
    ip_configurations:
      - name: default
        private_ip_allocation_method: Static
        private_ip_address: "10.0.0.{{ (item|int) + 2 }}"
  async: 300
  poll: 0
  register: interfaces_deploy
  with_sequence: "start=2 count={{ network_count }}" 

- name: Check Interface creation status
  async_status:
      jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 10
  loop: "{{ interfaces_deploy.results }}"

- name: Create network interface for Bastion
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: nic-internal1
    virtual_network: vnet
    subnet_name: vnet-internal
    ip_configurations:
      - name: default
        public_ip_address_name: public-ip
        primary: True
      - name: private
        private_ip_allocation_method: Dynamic
  register: output_nic_internal1

- name: Add SSH rule Bastion to nsg-vnet
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: nsg-vnet
    rules:
      - name: AllowSSHBastion
        protocol: "*"
        access: "Allow"
        priority: 110
        direction: Inbound
        destination_address_prefix: "{{ output_nic_internal1.state.ip_configurations[0].private_ip_address }}"
        destination_port_range: 22