---
- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: canadaeast

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group }}"
    name: vnet
    address_prefixes_cidr: "10.0.0.0/16"

- name: Create internal subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group }}"
    name: vnet-internal
    address_prefix_cidr: "10.0.0.0/24"
    virtual_network: vnet

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: Static
    name: public-ip
  register: output_ip

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip.state.ip_address }}"

- name: Export IP Address
  copy:
    content: "{{ output_ip.state.ip_address }}"
    dest: "creds/ip"

- name: Set nic_create variable
  set_fact:
    nic_create: []

- name: Compute Nic name Workers
  set_fact:
    nic_create: "{{ nic_create + [{'name':'nic-worker-' + item, 'ip':'10.0.0.' + (item + 3)  }] }}"
  with_sequence: "start=1 count={{ vm_config['worker']['count'] }}" 


- name: Compute Nic name Testers
  set_fact:
    nic_create: "{{ nic_create + [{'name': 'nic-test-' + item, 'ip':'10.0.0.' + ( item + 49 ) }] }}"
  with_sequence: "start=1 count={{ vm_config['test']['count'] }}" 
   
- name: Compute Nic name Monitor
  set_fact:
    nic_create: "{{ nic_create + [{'name': 'nic-monitor-1', 'ip':'10.0.0.205'}] }}"
  when: vm_config['monitor']['count'] == 1

- name: Show nic creation variable
  debug:
    msg: "{{ nic_create }}"


- name: Create network interfaces
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: "{{ item.name }}"
    virtual_network: vnet
    subnet_name: "vnet-internal"
    create_with_security_group: no
    ip_configurations:
      - name: default
        private_ip_allocation_method: Static
        private_ip_address: "{{ item.ip }}"
  async: 300
  poll: 0
  register: interfaces_deploy
  loop: "{{ nic_create }}"

# Master interface creation
- name: Create network interface for Bastion
  azure_rm_networkinterface:
    resource_group: "{{ resource_group }}"
    name: nic-master-1
    virtual_network: vnet
    subnet_name: vnet-internal
    ip_configurations:
      - name: default
        public_ip_address_name: public-ip
        primary: True
      - name: private
        private_ip_allocation_method: Static
        private_ip_address: "10.0.0.200"
  register: output_nic_master


- name: Add SSH rule Bastion to nsg-vnet
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: nsg-vnet
    rules:
      - name: AllowSSHBastion
        protocol: "*"
        access: "Allow"
        priority: 110
        direction: Inbound
        destination_address_prefix: "{{ output_nic_master.state.ip_configurations[0].private_ip_address }}"
        destination_port_range: 22

- name: Check interface creation status
  async_status:
      jid: "{{ item.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 10
  loop: "{{ interfaces_deploy.results }}"