---
# Install all the requiered dependencies on the VMs
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 

- hosts: master
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Configure Master node
      include: "roles/kubernetes-master/tasks/config.yml"
  

- hosts: workers
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Configure workers node
      include: "roles/kubernetes-workers/tasks/config.yml"
