---
# Install all the requiered dependencies on the VMs
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: master
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Configure Master node
      include: "roles/docker-master/tasks/hello.yml"
  

- hosts: workers
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Configure workers node
      include: "roles/docker-workers/tasks/hello.yml"
