---
# Deploy a helloworld container on all the nodes
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: master:workers
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Configure Master node
      include: "roles/docker-master/tasks/hello.yml"