---
# Remove all containers running on the workers and masters

- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: master:workers
  vars_files:
    - vars/default.yml
  become: yes
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info
  
    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
  
    - name: Remove Stoped docker containers
      shell: |
        docker rm $(docker ps -a -q);
      when: docker_info.containers != 0