---
# Install all the requiered dependencies on the VMs
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: workers:monitor:master:test
  vars_files:
    - vars/default.yml
  become: yes
  roles:
    - "docker-base"

- hosts: workers:master
  vars_files:
    - vars/default.yml
  become: yes
  roles:
    - "agent-monitor"