---
# Deploy influxdb and grafana
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: monitor
  vars_files:
    - vars/default.yml
  become: yes
  roles:
    - "docker-monitor"

- hosts: localhost
  gather_facts: False
  connection: local
  collections:
    - community.grafana
  vars:
    grafana_url: http://localhost:8000
  
  tasks:
    - name: Pause 30s to wait for grafana initialization
      pause:
        seconds: 30
      
    - name: Configure datasource
      grafana_datasource:
        name: "influxdb"
        grafana_url: "{{ grafana_url }}"
        ds_type: "influxdb"
        ds_url: "http://influxdb:8086"
        database: "metrics"
    
    - name: Import Dashboard Host
      grafana_dashboard:
        grafana_url: "{{ grafana_url }}"
        dashboard_url: https://grafana.com/api/dashboards/928/revisions/4/download

    - name: Import Dashboard Docker
      grafana_dashboard:
        grafana_url: "{{ grafana_url }}"
        dashboard_url: https://grafana.com/api/dashboards/1150/revisions/2/download