---
# Deploy influxdb and grafana
#
#
- hosts: localhost
  gather_facts: False
  vars_files:
    - vars/default.yml
  roles: 
    - "host-registration"

- hosts: monitor
  vars_files:
    - vars/default.yml
  become: yes
  roles:
    - "docker-monitor"