---
- name: Install telegraf
  apt:
    deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.3_amd64.deb
    state: present
  
- name: Copy the telegraf configuration file
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf

- name: Enable & Start telegraf
  systemd:
    name: telegraf
    enabled: yes
    state: started