---
- name: Install telegraf
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.16.2-1_amd64.deb
    state: present

- name: Create telegraf directory
  file:
    path: /etc/telegraf
    recurse: yes
    state: directory

- name: Copy the telegraf configuration file
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf

- name: Enable & Start telegraf
  systemd:
    name: telegraf
    enabled: yes
    state: started