---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Make sure to allow all trafic
  ufw:
    state: enabled
    policy: allow

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: 
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
    - 'gnupg-agent'
    - 'python3-pip'
    - 'virtualenv'
    - 'python3-setuptools'

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']

- name: Add {{ username }} to docker group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes

- name: Install Docker Module for Python
  pip:
    name: docker