---
- name: Setup docker network
  docker_network:
    name: 2org1peergoleveldb_solo_raft_default
    state: present
    driver: bridge

- name: Setup CA for organizations
  docker_container:
    auto_remove: no
    name: ca.org{{ inventory_hostname | replace('node-worker-','') }}.example.com
    image: hyperledger/fabric-ca:{{ fabric_version }}
    state: started
    env:
      FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
      FABRIC_CA_SERVER_CA_NAME: ca.org{{ inventory_hostname | replace('node-worker-','') }}.example.com
      FABRIC_CA_SERVER_CA_CERTFILE: /etc/hyperledger/fabric-ca-server-config/ca.org{{ inventory_hostname | replace('node-worker-','') }}.example.com-cert.pem
      FABRIC_CA_SERVER_CA_KEYFILE: /etc/hyperledger/fabric-ca-server-config/key.pem
      FABRIC_CA_SERVER_TLS_ENABLED: 'true'
      FABRIC_CA_SERVER_TLS_CERTFILE: /etc/hyperledger/fabric-ca-server-tls/tlsca.org{{ inventory_hostname | replace('node-worker-','') }}.example.com-cert.pem
      FABRIC_CA_SERVER_TLS_KEYFILE: /etc/hyperledger/fabric-ca-server-tls/key.pem
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    published_ports:
      - 7054:7054
    volumes:
      - /mnt/shared/config_solo_raft/crypto-config/peerOrganizations/org{{ inventory_hostname | replace('node-worker-','') }}.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - /mnt/shared/config_solo_raft/crypto-config/peerOrganizations/org{{ inventory_hostname | replace('node-worker-','') }}.example.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
    volume_driver: local
    networks:
      - name: 2org1peergoleveldb_solo_raft_default

- name: Setup Peer for organizations
  docker_container:
    auto_remove: no
    name: peer0.org{{ inventory_hostname | replace('node-worker-','') }}.example.com
    image: hyperledger/fabric-peer:{{ fabric_version }}
    state: started
    env:
      CORE_LOGGING_PEER: debug
      CORE_VM_DOCKER_ATTACHSTDOUT: 'true'
      CORE_CHAINCODE_DEPLOYTIMEOUT: 1000s
      CORE_CHAINCODE_STARTUPTIMEOUT: 1000s
      CORE_CHAINCODE_EXECUTETIMEOUT: 999999s
      FABRIC_LOGGING_SPEC: grpc=WARN:WARN
      CORE_CHAINCODE_LOGGING_LEVEL: debug
      CORE_CHAINCODE_LOGGING_SHIM: debug
      CORE_VM_ENDPOINT: unix:///host/var/run/docker.sock
      CORE_PEER_ID: peer0.org{{ inventory_hostname | replace('node-worker-','') }}.example.com
      CORE_PEER_ENDORSER_ENABLED: 'true'
      CORE_PEER_LOCALMSPID: Org{{ inventory_hostname | replace('node-worker-','') }}MSP
      CORE_PEER_MSPCONFIGPATH: /etc/hyperledger/msp/peer/msp/
      CORE_PEER_ADDRESS: 0.0.0.0:7051
      CORE_PEER_GOSSIP_USELEADERELECTION: 'true'
      CORE_PEER_GOSSIP_ORGLEADER: 'false'
      CORE_PEER_GOSSIP_EXTERNALENDPOINT: 0.0.0.0:7051
      CORE_PEER_TLS_ENABLED: 'true'
      CORE_PEER_TLS_KEY_FILE: /etc/hyperledger/msp/peer/tls/server.key
      CORE_PEER_TLS_CERT_FILE: /etc/hyperledger/msp/peer/tls/server.crt
      CORE_PEER_TLS_ROOTCERT_FILE: /etc/hyperledger/msp/peer/tls/ca.crt
      CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE: 2org1peergoleveldb_solo_raft_default
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    published_ports:
      - 7051:7051
    volumes:
      - /var/run/:/host/var/run/
      - /mnt/shared/config_solo_raft/crypto-config/peerOrganizations/org{{ inventory_hostname | replace('node-worker-','') }}.example.com/peers/peer0.org{{ inventory_hostname | replace('node-worker-','') }}.example.com/:/etc/hyperledger/msp/peer
    volume_driver: local

    networks:
      - name: 2org1peergoleveldb_solo_raft_default