---
- name: Setup mongodb-shard
  docker_container:
    auto_remove: no
    name: mongodb-shard
    image: bitnami/mongodb-sharded:latest
    state: started
    env:
      MONGODB_SHARDING_MODE: shardsvr
      MONGODB_MONGOS_HOST: "{{ hostvars['node-1']['ansible_default_ipv4']['address'] }}"
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_REPLICA_SET_NAME: shard-{{ ansible_hostname }}
    
    published_ports:
      - 27018:27018
    volumes:
      - 'shard0_data:/bitnami'
    volume_driver: local