version: '3'
services:
  mongos:
    container_name: mongos
    image: bitnami/mongodb-sharded:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  
  mongodb-cfg:
    container_name: mongodb-cfg
    image: bitnami/mongodb-sharded:latest
    restart: always
    expose:
      - 27019
    environment:
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=config-replicaset
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - 'cfg_data:/bitnami'
  
  mongodb-shard1:
    container_name: mongodb-shard1
    image: bitnami/mongodb-sharded:latest
    restart: always
    expose:
      - 27018
    environment:
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard-1
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - 'shard-1:/bitnami'

  mongodb-shard2:
    container_name: mongodb-shard2
    image: bitnami/mongodb-sharded:latest
    restart: always
    expose:
      - 27018
    environment:
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard-2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    volumes:
      - 'shard-2:/bitnami'
volumes:
  shard-1:
  shard-2:
  cfg_data:
    