---
- name: Create cluster list
  set_fact:
    cluster_list: []
  
- name: Update cluster list
  set_fact:
    cluster_list: "{{ cluster_list + [ 'worker-'+ item + '.hosts.' + dnszone ]}}"
  with_sequence: "start=1 count={{ vm_config['worker']['count'] }}"

- name: Add master to cluster list
  set_fact:
    cluster_list: "{{ cluster_list + [ 'master-1.hosts.' + dnszone ]}}"

- name: Config peers
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ cluster_list }}"

- name: Craft command volume create
  set_fact:
    gluster_create_command: ""

- name: Craft command volume create loop
  set_fact:
    gluster_create_command: "{{ gluster_create_command + item + ':/srv/gluster/brick/shared/ ' }}"
  loop: "{{ cluster_list }}"
    
- name: Create a volume gluster with the command because ansible gluster is broken
  command: gluster volume create shared replica {{ vm_config['worker']['count'] + 1 }} {{ gluster_create_command }} force
  run_once: true

- name: Start volume
  command: gluster volume start shared
  run_once: true