---
- name: Install Gluster Server
  apt:
    name: glusterfs-server
    state: present

- name: Create directory for gluster volume data
  file:
    path: /srv/gluster/brick/
    recurse: yes
    state: directory

- name: Ensure glusterfs is started
  systemd:
    name: glusterd
    enabled: yes
    state: restarted