---
- name: Setup docker network
  docker_network:
    name: mongodb-network
    state: present

- name: Setup mongos
  docker_container:
    auto_remove: no
    name: mongos
    image: bitnami/mongodb-sharded:latest
    state: started
    env:
      MONGODB_SHARDING_MODE: mongos
      MONGODB_CFG_PRIMARY_HOST: mongodb-cfg
      MONGODB_CFG_REPLICA_SET_NAME: cfgreplicaset
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ROOT_PASSWORD: password123
    networks:
      - name: mongodb-network
    published_ports:
      - 27017:27017

- name: Setup mongodb-cfg
  docker_container:
    auto_remove: no
    name: mongodb-cfg
    image: bitnami/mongodb-sharded:latest
    state: started
    env:
      MONGODB_SHARDING_MODE: configsvr
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_REPLICA_SET_NAME: config-replicaset
    networks:
      - name: mongodb-network
    published_ports:
      - 27019:27019
    volumes:
      - 'cfg_data:/bitnami'
    volume_driver: local