---
- name: Create docker directory
  file:
    path: /home/$HOME/docker
    state: directory
    recurse: yes

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/$HOME/docker/

- name: Deploy docker-compose.yml
  docker_compose:
    project_src: docker