---
- name: Add master vm
  add_host:
    ansible_host: "{{ lookup('file', 'creds/ip') }}"
    ansible_user: "{{ username }}"
    name: node-master-1
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    groups: master

- name: Add worker vm
  add_host:
    ansible_host: 127.0.0.1
    ansible_user: "{{ username }}"
    ansible_port: "{{ port_base -1 + (item|int) }}"
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    name: "node-worker-{{ item }}"
    groups: workers
  with_sequence: "start=1 count={{ (vm_config['worker']['count'] | int) }}"

- name: Add tests vm
  add_host:
    ansible_host: 127.0.0.1
    ansible_user: "{{ username }}"
    ansible_port: "{{ port_base -1 + 50 + (item|int) }}"
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    name: "node-test-{{ item }}"
    groups: testers
  with_sequence: "start=1 count={{ (vm_config['test']['count'] | int) }}"

- name: Add monitoring
  add_host:
    ansible_host: 127.0.0.1
    ansible_user: "{{ username }}"
    ansible_port: "{{ port_base + 205 }}"
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    name: "node-monitor-1"
    groups: monitor
  when: vm_config['monitor']['count'] == 1

