---
- name: Add master node
  add_host:
    hostname: "{{ lookup('file', 'creds/ip') }}"
    ansible_user: "{{ username }}"
    name: node-1
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    groups: master

- name: Add worker
  add_host:
    ansible_host: 127.0.0.1
    ansible_user: "{{ username }}"
    ansible_port: "{{ port_base + (item|int) }}"
    ansible_ssh_private_key_file: creds/ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3

    name: "node-{{ item }}"
    groups: workers
  with_sequence: "start=2 count={{ (amount_worker | int) }}"